// frontend/src/pages/Dashboard.vue
<script setup lang="ts">
import { computed } from "vue";
import { useQuery } from "@tanstack/vue-query";
import { useRouter } from "vue-router";
import { API, STATE_ORDER, type GranuleState } from "../api";
import { fmtAge, levelLabel, stateLabel } from "../i18n";
import Badge from "../ui/Badge.vue";
import Card from "../ui/Card.vue";
import EmptyState from "../ui/EmptyState.vue";
import PageHeader from "../ui/PageHeader.vue";
import Stat from "../ui/Stat.vue";
import StateBarChart from "./StateBarChart.vue";
import NodeStat from "./NodeStat.vue";
import OnboardingCard from "./OnboardingCard.vue";
import { Icon } from "../ui/Icon";

const router = useRouter();

const overview = useQuery({ queryKey: ["overview"], queryFn: API.overview });
const workers = useQuery({ queryKey: ["workers"], queryFn: API.workers });
const receivers = useQuery({ queryKey: ["receivers"], queryFn: API.receivers });
const inflight = useQuery({ queryKey: ["in-flight"], queryFn: () => API.inFlight(30) });
const stuckList = useQuery({
  queryKey: ["stuck"],
  queryFn: () => API.stuck(50),
  // No point fetching when nothing is stuck — the count comes from `overview`.
  enabled: computed(
    () =>
      Object.values(overview.data.value?.stuck_by_state ?? {}).reduce((a, b) => a + (b ?? 0), 0) > 0,
  ),
});

const counts = computed(() => overview.data.value?.state_counts ?? {});
const stuck = computed(() => overview.data.value?.stuck_by_state ?? {});
const stuckTotal = computed(() =>
  Object.values(stuck.value).reduce((a, b) => a + (b ?? 0), 0),
);
const failed = computed(() => (counts.value.failed ?? 0) + (counts.value.blacklisted ?? 0));
// Sum of every state except `deleted` — i.e. granules still occupying any
// resource (worker disk, receiver mailbox).
const inflightTotal = computed(() =>
  STATE_ORDER.reduce(
    (s, k) => (k === "deleted" ? s : s + (counts.value[k] ?? 0)),
    0,
  ),
);
const done = computed(() => counts.value.deleted ?? 0);

const stuckHint = computed(() =>
  stuckTotal.value > 0
    ? Object.entries(stuck.value)
        .map(([k, v]) => `${stateLabel(k as GranuleState)}:${v}`)
        .join(" · ")
    : "一切顺利",
);

const activeWorkers = computed(
  () =>
    (workers.data.value ?? []).filter(
      (w) => Date.now() - new Date(w.last_seen).getTime() < 120_000,
    ).length,
);
const activeReceivers = computed(
  () =>
    (receivers.data.value ?? []).filter(
      (r) => Date.now() - new Date(r.last_seen).getTime() < 120_000,
    ).length,
);

const hasChartData = computed(() => STATE_ORDER.some((s) => (counts.value[s] ?? 0) > 0));

const active = computed(() => inflight.data.value ?? []);

const firstRun = computed(
  () =>
    overview.isSuccess.value &&
    workers.isSuccess.value &&
    Object.keys(counts.value).length === 0 &&
    (workers.data.value?.length ?? 0) === 0,
);

const lastEvents = computed(() => overview.data.value?.last_events ?? []);
const stuckRows = computed(() => stuckList.data.value ?? []);
const stuckHours = computed(() => overview.data.value?.stuck_over_hours ?? 6);

function gotoGranule(batchId: string, granuleId: string) {
  router.push(`/batches/${batchId}?granule=${encodeURIComponent(granuleId)}`);
}

function fmtHours(h: number): string {
  if (h < 24) return `${h.toFixed(1)} 小时`;
  return `${(h / 24).toFixed(1)} 天`;
}
</script>

<template>
  <div class="space-y-6">
    <PageHeader title="总览" description="管道健康一览 · SSE 实时更新" />

    <OnboardingCard v-if="firstRun" />

    <div class="grid grid-cols-2 gap-4 md:grid-cols-4">
      <Stat label="处理中" :value="inflightTotal.toLocaleString()" to="/batches">
        <template #icon><Icon name="pulse" /></template>
      </Stat>
      <Stat label="已完成" :value="done.toLocaleString()" tone="good" to="/batches">
        <template #icon><Icon name="check" /></template>
      </Stat>
      <Stat
        label="失败"
        :value="failed.toLocaleString()"
        :tone="failed > 0 ? 'bad' : 'default'"
        :to="failed > 0 ? '/events?level=error' : '/batches'"
      >
        <template #icon><Icon name="alert" /></template>
      </Stat>
      <Stat
        :label="`卡住 > ${stuckHours} 小时`"
        :value="stuckTotal.toLocaleString()"
        :tone="stuckTotal > 0 ? 'warn' : 'default'"
        :hint="stuckHint"
      />
    </div>

    <div class="grid grid-cols-1 gap-4 lg:grid-cols-3">
      <Card
        title="各阶段数据粒数量"
        description="管线各阶段当前驻留数据粒"
        class-name="lg:col-span-2"
      >
        <div v-if="!hasChartData" class="flex h-56 items-center justify-center">
          <EmptyState title="暂无数据粒" />
        </div>
        <StateBarChart v-else :counts="counts" />
      </Card>

      <Card title="节点" description="集群健康度">
        <div class="space-y-3">
          <NodeStat
            label="工作节点"
            :value="activeWorkers"
            :total="workers.data.value?.length ?? 0"
            @click="router.push('/workers')"
          >
            <template #icon><Icon name="workers" /></template>
          </NodeStat>
          <NodeStat
            label="接收端"
            :value="activeReceivers"
            :total="receivers.data.value?.length ?? 0"
            @click="router.push('/receivers')"
          >
            <template #icon><Icon name="receivers" /></template>
          </NodeStat>
        </div>
      </Card>
    </div>

    <Card title="正在处理" description="近 30 条非终态数据粒" :padded="false">
      <template #action>
        <span class="rounded-full border border-border bg-subtle px-2.5 py-0.5 text-[11px] font-medium text-muted tabular-nums">
          {{ active.length > 0 ? `${active.length} 条` : "空闲" }}
        </span>
      </template>
      <EmptyState
        v-if="active.length === 0"
        title="当前没有正在处理的数据粒"
        description="新建批次后，活动条目会自动出现在这里。"
      />
      <div v-else class="overflow-x-auto">
        <table class="w-full text-sm">
          <thead class="bg-subtle/50 th-row">
            <tr>
              <th class="px-5 py-2.5">数据粒</th>
              <th class="px-2 py-2.5">批次</th>
              <th class="px-2 py-2.5">当前阶段</th>
              <th class="px-2 py-2.5">工作节点</th>
              <th class="px-5 py-2.5">更新</th>
            </tr>
          </thead>
          <tbody>
            <tr
              v-for="g in active"
              :key="g.granule_id"
              class="cursor-pointer border-t border-border/70 transition hover:bg-subtle/50"
              title="跳转到该数据粒详情"
              @click="gotoGranule(g.batch_id, g.granule_id)"
            >
              <td class="px-5 py-2.5 font-mono text-[11.5px]">{{ g.granule_id }}</td>
              <td class="px-2 py-2.5 font-mono text-[11.5px] text-muted">{{ g.batch_id }}</td>
              <td class="px-2 py-2.5">
                <Badge :tone="g.state" dot>{{ stateLabel(g.state) }}</Badge>
              </td>
              <td
                class="px-2 py-2.5 font-mono text-[11.5px] text-muted"
                @click.stop
              >
                <RouterLink
                  v-if="g.leased_by"
                  :to="`/workers?id=${encodeURIComponent(g.leased_by)}`"
                  class="transition hover:text-accent"
                  title="跳转到该 worker 卡片"
                >
                  {{ g.leased_by }}
                </RouterLink>
                <template v-else>—</template>
              </td>
              <td class="px-5 py-2.5 text-[11.5px] text-muted">{{ fmtAge(g.updated_at) }}</td>
            </tr>
          </tbody>
        </table>
      </div>
    </Card>

    <Card
      v-if="stuckTotal > 0"
      title="卡住的数据粒"
      :description="`非终态且 > ${stuckHours} 小时未推进 · 最旧者优先`"
      :padded="false"
    >
      <template #action>
        <span
          class="rounded-full border border-warning/40 bg-warning/10 px-2.5 py-0.5 text-[11px] font-medium text-warning tabular-nums"
        >
          {{ stuckRows.length }} / {{ stuckTotal }}
        </span>
      </template>
      <div class="overflow-x-auto">
        <table class="w-full text-sm">
          <thead class="bg-subtle/50 th-row">
            <tr>
              <th class="px-5 py-2.5">数据粒</th>
              <th class="px-2 py-2.5">批次</th>
              <th class="px-2 py-2.5">状态</th>
              <th class="px-2 py-2.5">领取方</th>
              <th class="px-2 py-2.5">滞留</th>
              <th class="px-5 py-2.5">错误</th>
            </tr>
          </thead>
          <tbody>
            <tr
              v-for="g in stuckRows"
              :key="g.granule_id"
              class="cursor-pointer border-t border-border/70 transition hover:bg-subtle/50"
              title="跳转到该数据粒详情"
              @click="gotoGranule(g.batch_id, g.granule_id)"
            >
              <td class="px-5 py-2.5 font-mono text-[11.5px]">{{ g.granule_id }}</td>
              <td class="px-2 py-2.5 font-mono text-[11.5px] text-muted">{{ g.batch_id }}</td>
              <td class="px-2 py-2.5">
                <Badge :tone="g.state" dot>{{ stateLabel(g.state) }}</Badge>
              </td>
              <td
                class="px-2 py-2.5 font-mono text-[11.5px] text-muted"
                @click.stop
              >
                <RouterLink
                  v-if="g.leased_by"
                  :to="`/workers?id=${encodeURIComponent(g.leased_by)}`"
                  class="transition hover:text-accent"
                >
                  {{ g.leased_by }}
                </RouterLink>
                <template v-else>—</template>
              </td>
              <td class="px-2 py-2.5 text-[11.5px] text-warning tabular-nums">
                {{ fmtHours(g.age_hours) }}
              </td>
              <td class="max-w-[320px] truncate px-5 py-2.5 font-mono text-[11.5px] text-danger">
                {{ g.error ?? "—" }}
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </Card>

    <Card title="最近事件" description="后台 10 条" :padded="false">
      <div class="divide-y divide-border/60">
        <div
          v-for="e in lastEvents"
          :key="e.id"
          class="flex items-center gap-3 px-5 py-2.5 font-mono text-[11.5px] transition hover:bg-subtle/50"
        >
          <span class="w-20 shrink-0 text-muted">{{ fmtAge(e.ts) }}</span>
          <Badge :tone="e.level" dot>{{ levelLabel(e.level) }}</Badge>
          <span class="w-32 shrink-0 truncate text-muted">{{ e.source }}</span>
          <span class="flex-1 truncate text-text">{{ e.message }}</span>
        </div>
        <EmptyState v-if="lastEvents.length === 0" title="暂无事件" />
      </div>
    </Card>
  </div>
</template>

// frontend/src/pages/Dashboard.tsx
import { useQuery } from "@tanstack/react-query";
import ReactECharts from "echarts-for-react";
import { useNavigate } from "react-router-dom";
import { API, GranuleState } from "../api";
import { Badge, Card, Stat } from "../ui";
import { fmtAge, levelLabel, stateLabel } from "../i18n";

const ORDER: GranuleState[] = [
  "pending", "downloading", "downloaded", "processing", "processed", "uploaded", "acked", "deleted",
];

const COLORS: Record<GranuleState, string> = {
  pending: "#475569",
  downloading: "#0ea5e9",
  downloaded: "#0284c7",
  processing: "#6366f1",
  processed: "#4f46e5",
  uploaded: "#8b5cf6",
  acked: "#10b981",
  deleted: "#059669",
  failed: "#f43f5e",
  blacklisted: "#9f1239",
};

export function Dashboard() {
  const navigate = useNavigate();
  const overview = useQuery({ queryKey: ["overview"], queryFn: API.overview });
  const workers = useQuery({ queryKey: ["workers"], queryFn: API.workers });
  const receivers = useQuery({ queryKey: ["receivers"], queryFn: API.receivers });
  const inflight = useQuery({ queryKey: ["in-flight"], queryFn: () => API.inFlight(30) });

  const counts = overview.data?.state_counts ?? {};
  const stuck = overview.data?.stuck_by_state ?? {};
  const stuckTotal = Object.values(stuck).reduce((a, b) => a + b, 0);
  const failed = (counts.failed ?? 0) + (counts.blacklisted ?? 0);
  const inflightTotal = ORDER.slice(0, 7).reduce((s, k) => s + (counts[k] ?? 0), 0);
  const done = counts.deleted ?? 0;

  const activeWorkers = (workers.data ?? []).filter(
    (w) => Date.now() - new Date(w.last_seen).getTime() < 120_000,
  ).length;
  const activeReceivers = (receivers.data ?? []).filter(
    (r) => Date.now() - new Date(r.last_seen).getTime() < 120_000,
  ).length;

  // Horizontal bar: one row per non-empty state, ordered top-to-bottom as the
  // pipeline flows. ECharts renders y-axis top-down when we reverse the arrays.
  const barStates = ORDER.filter((s) => (counts[s] ?? 0) > 0);
  const barCategories = [...barStates].reverse().map((s) => stateLabel(s));
  const barValues = [...barStates].reverse().map((s) => ({
    value: counts[s]!,
    itemStyle: { color: COLORS[s] },
  }));

  const active = inflight.data ?? [];

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-xl font-semibold">总览</h1>
        <p className="text-xs text-muted">管道健康一览 · SSE 实时更新</p>
      </div>

      <div className="grid grid-cols-2 gap-4 md:grid-cols-4">
        <Stat label="处理中" value={inflightTotal} to="/batches" />
        <Stat label="已完成" value={done} tone="good" to="/batches" />
        <Stat
          label="失败"
          value={failed}
          tone={failed > 0 ? "bad" : "default"}
          to={failed > 0 ? "/events?level=error" : "/batches"}
        />
        <Stat
          label="卡住 > 6 小时"
          value={stuckTotal}
          tone={stuckTotal > 0 ? "warn" : "default"}
          hint={stuckTotal > 0 ? Object.entries(stuck).map(([k, v]) => `${stateLabel(k as GranuleState)}:${v}`).join(" · ") : undefined}
          to="/events?level=warn"
        />
      </div>

      <div className="grid grid-cols-1 gap-4 lg:grid-cols-3">
        <Card title="各阶段数据粒数量" className="lg:col-span-2">
          {barStates.length === 0 ? (
            <div className="flex h-56 items-center justify-center text-sm text-muted">暂无数据粒。</div>
          ) : (
            <ReactECharts
              style={{ height: 256 }}
              option={{
                grid: { left: 80, right: 48, top: 10, bottom: 28, containLabel: false },
                tooltip: {
                  trigger: "axis",
                  axisPointer: { type: "shadow" },
                  formatter: (params: { name: string; value: number }[]) =>
                    params.map((p) => `${p.name}: <b>${p.value.toLocaleString()}</b>`).join("<br/>"),
                },
                xAxis: {
                  type: "value",
                  name: "数据粒数",
                  nameLocation: "middle",
                  nameGap: 22,
                  nameTextStyle: { color: "#94a3b8", fontSize: 10 },
                  axisLine: { lineStyle: { color: "#475569" } },
                  axisLabel: { color: "#94a3b8" },
                  splitLine: { lineStyle: { color: "#1e293b" } },
                  minInterval: 1,
                },
                yAxis: {
                  type: "category",
                  data: barCategories,
                  axisLine: { lineStyle: { color: "#475569" } },
                  axisLabel: { color: "#e2e8f0" },
                },
                series: [
                  {
                    type: "bar",
                    data: barValues,
                    label: {
                      show: true,
                      position: "right",
                      color: "#e2e8f0",
                      formatter: "{c}",
                    },
                    barMaxWidth: 20,
                  },
                ],
              }}
            />
          )}
        </Card>

        <Card title="节点">
          <div className="space-y-3">
            <button
              type="button"
              onClick={() => navigate("/workers")}
              className="flex w-full items-baseline justify-between rounded px-1 py-1 text-left transition hover:bg-bg"
            >
              <span className="text-sm text-muted">在线工作节点 →</span>
              <span className="tabular-nums">
                <span className="text-xl font-semibold">{activeWorkers}</span>
                <span className="text-muted"> / {workers.data?.length ?? 0}</span>
              </span>
            </button>
            <button
              type="button"
              onClick={() => navigate("/receivers")}
              className="flex w-full items-baseline justify-between rounded px-1 py-1 text-left transition hover:bg-bg"
            >
              <span className="text-sm text-muted">在线接收端 →</span>
              <span className="tabular-nums">
                <span className="text-xl font-semibold">{activeReceivers}</span>
                <span className="text-muted"> / {receivers.data?.length ?? 0}</span>
              </span>
            </button>
          </div>
        </Card>
      </div>

      <Card
        title="正在处理"
        action={
          <span className="text-xs text-muted">
            {active.length > 0 ? `${active.length} 条` : "空闲"}
          </span>
        }
      >
        {active.length === 0 ? (
          <div className="py-6 text-center text-sm text-muted">当前没有正在处理的数据粒。</div>
        ) : (
          <table className="w-full text-sm">
            <thead className="text-left text-xs uppercase tracking-wide text-muted">
              <tr>
                <th className="pb-2">数据粒</th>
                <th className="pb-2">批次</th>
                <th className="pb-2">当前阶段</th>
                <th className="pb-2">工作节点</th>
                <th className="pb-2">更新</th>
              </tr>
            </thead>
            <tbody>
              {active.map((g) => {
                const href = `/batches/${g.batch_id}?granule=${encodeURIComponent(g.granule_id)}`;
                return (
                  <tr
                    key={g.granule_id}
                    onClick={() => navigate(href)}
                    className="cursor-pointer border-t border-border transition hover:bg-bg"
                    title="跳转到该数据粒详情"
                  >
                    <td className="py-2 pr-4 font-mono text-xs">{g.granule_id}</td>
                    <td className="py-2 pr-4 font-mono text-xs text-muted">{g.batch_id}</td>
                    <td className="py-2 pr-4">
                      <Badge tone={g.state}>{stateLabel(g.state)}</Badge>
                    </td>
                    <td className="py-2 pr-4 font-mono text-xs text-muted">{g.leased_by ?? "—"}</td>
                    <td className="py-2 pr-4 text-xs text-muted">{fmtAge(g.updated_at)}</td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        )}
      </Card>

      <Card title="最近事件">
        <div className="space-y-1 font-mono text-xs">
          {(overview.data?.last_events ?? []).map((e) => (
            <div key={e.id} className="flex items-center gap-3">
              <span className="w-20 shrink-0 text-muted">{fmtAge(e.ts)}</span>
              <Badge tone={e.level}>{levelLabel(e.level)}</Badge>
              <span className="w-28 shrink-0 truncate text-muted">{e.source}</span>
              <span className="truncate">{e.message}</span>
            </div>
          ))}
          {(overview.data?.last_events.length ?? 0) === 0 && (
            <div className="text-sm text-muted">无近期事件。</div>
          )}
        </div>
      </Card>
    </div>
  );
}
