// frontend/src/pages/Events.vue
<script setup lang="ts">
import { computed, ref, watch } from "vue";
import { useQuery } from "@tanstack/vue-query";
import { useRoute, useRouter } from "vue-router";
import { API, type EventRow } from "../api";
import { fmtAge, levelLabel } from "../i18n";
import Badge from "../ui/Badge.vue";
import Card from "../ui/Card.vue";
import EmptyState from "../ui/EmptyState.vue";
import PageHeader from "../ui/PageHeader.vue";
import SelectInput from "../ui/SelectInput.vue";
import Segmented from "../ui/Segmented.vue";
import Spinner from "../ui/Spinner.vue";
import TextInput from "../ui/TextInput.vue";
import { Icon } from "../ui/Icon";

type Level = "all" | "warn" | "error";
const LEVEL_FILTERS: { value: Level; label: string }[] = [
  { value: "all", label: "全部" },
  { value: "warn", label: "警告" },
  { value: "error", label: "错误" },
];

const route = useRoute();
const router = useRouter();

const initLevel = (route.query.level as Level | undefined) ?? "all";
const filter = ref<Level>(
  (["all", "warn", "error"] as Level[]).includes(initLevel) ? initLevel : "all",
);
const search = ref((route.query.q as string | undefined) ?? "");
const batchFilter = ref((route.query.batch as string | undefined) ?? "");
// Server-side exact-match filter on Event.source — used by per-node drill-downs
// (worker / receiver cards link here with ?source=<id>). Reset rows when it
// changes so we re-fetch a clean page rather than mixing old global rows in.
const sourceFilter = ref((route.query.source as string | undefined) ?? "");
const rows = ref<EventRow[]>([]);
const expanded = ref<Set<number>>(new Set());
const loadingOlder = ref(false);
const hasMoreOlder = ref(true);

watch([filter, search, batchFilter, sourceFilter], ([f, s, b, src]) => {
  const next: Record<string, string> = {};
  if (f !== "all") next.level = f;
  if (s) next.q = s;
  if (b) next.batch = b;
  if (src) next.source = src;
  router.replace({ query: next });
});

watch(sourceFilter, () => {
  rows.value = [];
  hasMoreOlder.value = true;
});

const q = useQuery({
  queryKey: computed(() => ["events", { source: sourceFilter.value }]),
  queryFn: () => API.events(rows.value[0]?.id ?? 0, 200, undefined, sourceFilter.value || undefined),
});

watch(
  () => q.data.value,
  (data) => {
    if (!data || data.length === 0) return;
    const seen = new Set(rows.value.map((r) => r.id));
    const fresh = data.filter((r) => !seen.has(r.id));
    if (fresh.length === 0) return;
    rows.value = [...fresh, ...rows.value].slice(0, 500);
  },
);

async function loadOlder() {
  const oldest = rows.value[rows.value.length - 1]?.id;
  if (oldest === undefined || loadingOlder.value) return;
  loadingOlder.value = true;
  try {
    const older = await API.events(0, 200, oldest, sourceFilter.value || undefined);
    if (older.length === 0) {
      hasMoreOlder.value = false;
      return;
    }
    const seen = new Set(rows.value.map((r) => r.id));
    rows.value = [...rows.value, ...older.filter((r) => !seen.has(r.id))];
    if (older.length < 200) hasMoreOlder.value = false;
  } finally {
    loadingOlder.value = false;
  }
}

const batches = computed(() => {
  const s = new Set<string>();
  for (const r of rows.value) if (r.batch_id) s.add(r.batch_id);
  return [...s].sort();
});

const needle = computed(() => search.value.trim().toLowerCase());

const visible = computed(() =>
  rows.value.filter((r) => {
    if (filter.value !== "all" && r.level !== filter.value) return false;
    if (batchFilter.value && r.batch_id !== batchFilter.value) return false;
    if (needle.value) {
      const hay = `${r.source} ${r.message} ${r.granule_id ?? ""} ${r.batch_id ?? ""}`.toLowerCase();
      if (!hay.includes(needle.value)) return false;
    }
    return true;
  }),
);

function isLong(msg: string) {
  return msg.length > 160 || msg.includes("\n");
}

function toggle(id: number) {
  const next = new Set(expanded.value);
  if (next.has(id)) next.delete(id);
  else next.add(id);
  expanded.value = next;
}

function clearAll() {
  search.value = "";
  batchFilter.value = "";
  sourceFilter.value = "";
  filter.value = "all";
}

type HighlightSeg = { text: string; mark: boolean };
function highlight(text: string, n: string): HighlightSeg[] {
  if (!n) return [{ text, mark: false }];
  const idx = text.toLowerCase().indexOf(n);
  if (idx < 0) return [{ text, mark: false }];
  return [
    { text: text.slice(0, idx), mark: false },
    { text: text.slice(idx, idx + n.length), mark: true },
    { text: text.slice(idx + n.length), mark: false },
  ];
}
</script>

<template>
  <div class="space-y-6">
    <PageHeader
      title="事件日志"
      description="所有 Orchestrator / Worker / Receiver 上报事件的合并视图"
    >
      <template #actions>
        <span class="rounded-full border border-border bg-subtle px-3 py-1 text-[11px] font-medium tabular-nums text-muted">
          <span class="text-text">{{ visible.length }}</span> / {{ rows.length }} 条
        </span>
      </template>
    </PageHeader>

    <Card :padded="false">
      <div class="flex flex-wrap items-center gap-2 border-b border-border/60 px-5 py-3.5">
        <div class="min-w-[260px] flex-1">
          <TextInput
            v-model="search"
            placeholder="搜索：message / source / granule_id / batch_id"
            aria-label="搜索事件"
          >
            <template #leftIcon>
              <Icon name="search" :size="13" />
            </template>
          </TextInput>
        </div>
        <SelectInput
          v-model="batchFilter"
          aria-label="按批次过滤"
          class="h-8 rounded-lg border border-border bg-surface px-2.5 text-xs text-text outline-none transition hover:border-accent/40 focus:border-accent"
        >
          <option value="">所有批次</option>
          <option v-for="b in batches" :key="b" :value="b">{{ b }}</option>
        </SelectInput>
        <Segmented v-model="filter" :options="LEVEL_FILTERS" />
        <span
          v-if="sourceFilter"
          class="inline-flex h-8 items-center gap-1.5 rounded-lg border border-accent/40 bg-accent/10 px-2.5 text-xs text-accent"
          title="按事件源（worker / receiver ID）过滤 — 服务端精确匹配"
        >
          源: <span class="font-mono">{{ sourceFilter }}</span>
          <button
            type="button"
            @click="sourceFilter = ''"
            class="text-accent/70 transition hover:text-accent"
            title="移除源过滤"
            aria-label="移除源过滤"
          >
            ×
          </button>
        </span>
        <button
          v-if="search || batchFilter || sourceFilter || filter !== 'all'"
          @click="clearAll"
          class="h-8 rounded-lg border border-border bg-surface px-2.5 text-xs text-muted transition hover:border-accent/40 hover:text-text"
        >
          清除
        </button>
      </div>

      <div class="max-h-[70vh] overflow-auto font-mono">
        <EmptyState
          v-if="visible.length === 0"
          :title="rows.length === 0 ? '暂无事件' : '当前筛选条件下没有匹配'"
        />
        <ul v-else class="divide-y divide-border/50">
          <li
            v-for="e in visible"
            :key="e.id"
            class="flex items-start gap-3 px-5 py-2 text-[11.5px] transition hover:bg-subtle/40"
          >
            <span class="w-20 shrink-0 text-muted">{{ fmtAge(e.ts) }}</span>
            <Badge :tone="e.level" dot>{{ levelLabel(e.level) }}</Badge>
            <span class="w-32 shrink-0 truncate text-muted" :title="e.source">{{ e.source }}</span>
            <span
              :class="
                isLong(e.message) && !expanded.has(e.id)
                  ? 'flex-1 cursor-pointer truncate hover:text-text'
                  : 'flex-1 break-all whitespace-pre-wrap'
              "
              :title="isLong(e.message) && !expanded.has(e.id) ? '点击展开完整消息' : undefined"
              @click="isLong(e.message) && toggle(e.id)"
            >
              <template v-for="(seg, i) in highlight(e.message, needle)" :key="i">
                <mark v-if="seg.mark" class="rounded bg-warning/30 px-0.5 text-warning">{{ seg.text }}</mark>
                <template v-else>{{ seg.text }}</template>
              </template>
              <button
                v-if="isLong(e.message)"
                type="button"
                @click.stop="toggle(e.id)"
                class="ml-2 text-[10px] text-muted hover:text-accent"
              >
                {{ expanded.has(e.id) ? "收起" : "展开" }}
              </button>
            </span>
            <template v-if="e.granule_id">
              <RouterLink
                v-if="e.batch_id"
                :to="`/batches/${e.batch_id}?granule=${encodeURIComponent(e.granule_id)}`"
                class="shrink-0 truncate text-muted transition hover:text-accent"
                :title="`跳转到 ${e.batch_id} 中的 ${e.granule_id}`"
              >
                {{ e.granule_id }}
              </RouterLink>
              <span v-else class="shrink-0 truncate text-muted">{{ e.granule_id }}</span>
            </template>
          </li>
        </ul>
        <div
          v-if="rows.length > 0"
          class="flex items-center justify-center border-t border-border/60 px-5 py-3"
        >
          <button
            v-if="hasMoreOlder"
            type="button"
            @click="loadOlder"
            :disabled="loadingOlder"
            class="flex items-center gap-2 rounded-lg border border-border bg-surface px-3 py-1.5 text-[11.5px] text-muted transition hover:border-accent/40 hover:text-text disabled:cursor-not-allowed disabled:opacity-50"
          >
            <Spinner v-if="loadingOlder" :size="12" />
            {{ loadingOlder ? "加载中…" : "加载更早事件" }}
          </button>
          <span v-else class="text-[11px] text-muted">已加载到最早事件</span>
        </div>
      </div>
    </Card>
  </div>
</template>

// frontend/src/pages/Events.tsx
import { useQuery } from "@tanstack/react-query";
import { useEffect, useMemo, useState } from "react";
import { Link, useSearchParams } from "react-router-dom";
import { API, EventRow } from "../api";
import { Badge, Card, EmptyState, PageHeader, Segmented, Spinner, TextInput } from "../ui";
import { fmtAge, levelLabel } from "../i18n";
import { IconSearch } from "../icons";

const LEVEL_FILTERS: { value: "all" | "warn" | "error"; label: string }[] = [
  { value: "all", label: "全部" },
  { value: "warn", label: "警告" },
  { value: "error", label: "错误" },
];

export function Events() {
  const [urlParams, setUrlParams] = useSearchParams();
  const initLevel = (urlParams.get("level") as "all" | "warn" | "error" | null) ?? "all";
  const initSearch = urlParams.get("q") ?? "";
  const initBatch = urlParams.get("batch") ?? "";
  const [filter, setFilter] = useState<"all" | "warn" | "error">(
    ["all", "warn", "error"].includes(initLevel) ? initLevel : "all",
  );
  const [search, setSearch] = useState(initSearch);
  const [batchFilter, setBatchFilter] = useState<string>(initBatch);
  const [rows, setRows] = useState<EventRow[]>([]);
  const [expanded, setExpanded] = useState<Set<number>>(new Set());
  const [loadingOlder, setLoadingOlder] = useState(false);
  const [hasMoreOlder, setHasMoreOlder] = useState(true);

  useEffect(() => {
    const next = new URLSearchParams();
    if (filter !== "all") next.set("level", filter);
    if (search) next.set("q", search);
    if (batchFilter) next.set("batch", batchFilter);
    setUrlParams(next, { replace: true });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [filter, search, batchFilter]);

  const q = useQuery({
    queryKey: ["events"],
    queryFn: async () => API.events(rows[0]?.id ?? 0, 200),
  });

  useEffect(() => {
    if (!q.data || q.data.length === 0) return;
    setRows((prev) => {
      const seen = new Set(prev.map((r) => r.id));
      const fresh = q.data!.filter((r) => !seen.has(r.id));
      if (fresh.length === 0) return prev;
      return [...fresh, ...prev].slice(0, 500);
    });
  }, [q.data]);

  const loadOlder = async () => {
    const oldest = rows[rows.length - 1]?.id;
    if (oldest === undefined || loadingOlder) return;
    setLoadingOlder(true);
    try {
      const older = await API.events(0, 200, oldest);
      if (older.length === 0) {
        setHasMoreOlder(false);
        return;
      }
      setRows((prev) => {
        const seen = new Set(prev.map((r) => r.id));
        return [...prev, ...older.filter((r) => !seen.has(r.id))];
      });
      if (older.length < 200) setHasMoreOlder(false);
    } finally {
      setLoadingOlder(false);
    }
  };

  const batches = useMemo(() => {
    const s = new Set<string>();
    for (const r of rows) if (r.batch_id) s.add(r.batch_id);
    return Array.from(s).sort();
  }, [rows]);

  const needle = search.trim().toLowerCase();
  const visible = useMemo(
    () =>
      rows.filter((r) => {
        if (filter !== "all" && r.level !== filter) return false;
        if (batchFilter && r.batch_id !== batchFilter) return false;
        if (needle) {
          const hay = `${r.source} ${r.message} ${r.granule_id ?? ""} ${r.batch_id ?? ""}`.toLowerCase();
          if (!hay.includes(needle)) return false;
        }
        return true;
      }),
    [rows, filter, batchFilter, needle],
  );

  const toggle = (id: number) =>
    setExpanded((s) => {
      const next = new Set(s);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });

  return (
    <div className="space-y-6">
      <PageHeader
        title="事件日志"
        description="所有 Orchestrator / Worker / Receiver 上报事件的合并视图"
        actions={
          <span className="rounded-full border border-border bg-subtle px-3 py-1 text-[11px] font-medium tabular-nums text-muted">
            <span className="text-text">{visible.length}</span> / {rows.length} 条
          </span>
        }
      />

      <Card padded={false}>
        <div className="flex flex-wrap items-center gap-2 border-b border-border/60 px-5 py-3.5">
          <div className="min-w-[260px] flex-1">
            <TextInput
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              placeholder="搜索：message / source / granule_id / batch_id"
              aria-label="搜索事件"
              leftIcon={<IconSearch width={13} height={13} />}
            />
          </div>
          <select
            value={batchFilter}
            onChange={(e) => setBatchFilter(e.target.value)}
            aria-label="按批次过滤"
            className="h-8 rounded-lg border border-border bg-surface px-2.5 text-xs text-text outline-none transition hover:border-accent/40 focus:border-accent"
          >
            <option value="">所有批次</option>
            {batches.map((b) => (
              <option key={b} value={b}>{b}</option>
            ))}
          </select>
          <Segmented<"all" | "warn" | "error">
            value={filter}
            onChange={setFilter}
            options={LEVEL_FILTERS}
          />
          {(search || batchFilter || filter !== "all") && (
            <button
              onClick={() => {
                setSearch("");
                setBatchFilter("");
                setFilter("all");
              }}
              className="h-8 rounded-lg border border-border bg-surface px-2.5 text-xs text-muted transition hover:border-accent/40 hover:text-text"
            >
              清除
            </button>
          )}
        </div>

        <div className="max-h-[70vh] overflow-auto font-mono">
          {visible.length === 0 ? (
            <EmptyState
              title={rows.length === 0 ? "暂无事件" : "当前筛选条件下没有匹配"}
            />
          ) : (
            <ul className="divide-y divide-border/50">
              {visible.map((e) => {
                const isLong = e.message.length > 160 || e.message.includes("\n");
                const open = expanded.has(e.id);
                return (
                  <li key={e.id} className="flex items-start gap-3 px-5 py-2 text-[11.5px] transition hover:bg-subtle/40">
                    <span className="w-20 shrink-0 text-muted">{fmtAge(e.ts)}</span>
                    <Badge tone={e.level} dot>{levelLabel(e.level)}</Badge>
                    <span className="w-32 shrink-0 truncate text-muted" title={e.source}>
                      {e.source}
                    </span>
                    <span
                      className={`flex-1 ${isLong && !open ? "cursor-pointer truncate hover:text-text" : "break-all whitespace-pre-wrap"}`}
                      onClick={() => isLong && toggle(e.id)}
                      title={isLong && !open ? "点击展开完整消息" : undefined}
                    >
                      {highlight(e.message, needle)}
                      {isLong && (
                        <button
                          type="button"
                          onClick={(ev) => {
                            ev.stopPropagation();
                            toggle(e.id);
                          }}
                          className="ml-2 text-[10px] text-muted hover:text-accent"
                        >
                          {open ? "收起" : "展开"}
                        </button>
                      )}
                    </span>
                    {e.granule_id &&
                      (e.batch_id ? (
                        <Link
                          to={`/batches/${e.batch_id}?granule=${encodeURIComponent(e.granule_id)}`}
                          className="shrink-0 truncate text-muted transition hover:text-accent"
                          title={`跳转到 ${e.batch_id} 中的 ${e.granule_id}`}
                        >
                          {e.granule_id}
                        </Link>
                      ) : (
                        <span className="shrink-0 truncate text-muted">{e.granule_id}</span>
                      ))}
                  </li>
                );
              })}
            </ul>
          )}
          {rows.length > 0 && (
            <div className="flex items-center justify-center border-t border-border/60 px-5 py-3">
              {hasMoreOlder ? (
                <button
                  type="button"
                  onClick={loadOlder}
                  disabled={loadingOlder}
                  className="flex items-center gap-2 rounded-lg border border-border bg-surface px-3 py-1.5 text-[11.5px] text-muted transition hover:border-accent/40 hover:text-text disabled:cursor-not-allowed disabled:opacity-50"
                >
                  {loadingOlder && <Spinner size={12} />}
                  {loadingOlder ? "加载中…" : "加载更早事件"}
                </button>
              ) : (
                <span className="text-[11px] text-muted">已加载到最早事件</span>
              )}
            </div>
          )}
        </div>
      </Card>
    </div>
  );
}

function highlight(text: string, needle: string) {
  if (!needle) return text;
  const idx = text.toLowerCase().indexOf(needle);
  if (idx < 0) return text;
  return (
    <>
      {text.slice(0, idx)}
      <mark className="rounded bg-warning/30 px-0.5 text-warning">
        {text.slice(idx, idx + needle.length)}
      </mark>
      {text.slice(idx + needle.length)}
    </>
  );
}
